# OPERACIONES CON NUMPY

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

## Suma de los elementos

In [4]:
suma = np.sum(arr)
suma

15

## Promedio

In [5]:
promedio = np.mean(arr)
promedio

3.0

## Mediana

In [6]:
mediana = np.median(arr)
mediana

3.0

## Producto

In [7]:
producto = np.prod(arr)
producto

120

## Desviación standar

In [9]:
desv = np.std(arr)
desv

1.4142135623730951

## Varianza

In [10]:
varianza = np.var(arr)
varianza

2.0

## Minimo - Máximo

In [11]:
minimo = np.min(arr)
print("El mínimo es: ", minimo)
maximo = np.max(arr)
print("El máximo es: ", maximo)

El mínimo es:  1
El máximo es:  5


## Suma acumlada

In [12]:
sumaacum = np.cumsum(arr)
sumaacum

array([ 1,  3,  6, 10, 15])

## Suma elemento a elemento

In [13]:
arr + arr

array([ 2,  4,  6,  8, 10])

## Resta elemento a elemento

In [14]:
arr - arr

array([0, 0, 0, 0, 0])

## Multiplicacion elemento a elemento

In [15]:
arr * arr

array([ 1,  4,  9, 16, 25])

## División (Elemento a elemento)

In [19]:
arr / arr

array([1., 1., 1., 1., 1.])